application:
  build: .
  dockerfile: ./Dockerfile.app
  expose:
    - "9000"
    - "9001"
  links:
    - redis
    - mysql
  container_name: app
  volumes:
    - ./project:/var/www/application

redis:
  image: redis:3.0.6
  container_name: cache

mysql:
  image: mysql
  container_name: database
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

webserver:
  build: .
  dockerfile: ./Dockerfile.nginx
  ports:
    - "80:80"
  container_name: nginx
  links:
    - application
  domainname: app.dev
  hostname: app.dev
  volumes:
    - ./logs/nginx:/var/log/nginx
  volumes_from:
    - application:ro
